name: meal_logging_app
description: A local-first meal logging app for GIKI students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI Components
  table_calendar: ^3.0.9
  
  # Notifications & Alarms
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  
  # Haptics
  vibration: ^2.0.0
  
  # Icons
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  firebase_core: ^4.4.0
  firebase_analytics: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#009688"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

flutter_native_splash:
  color: "#009688"
  color_dark: "#00796B"
  image: assets/icon/app_icon.png
  android: true
  ios: false
  web: false
  android_12:
    image: assets/icon/app_icon.png
    color: "#009688"
    color_dark: "#00796B"